### ISSUE TITLE
json loads вызовет исключение если payload не является json

### ISSUE THREAD

**Issue by timoniq** [dadyarri/jacob#1]
https://github.com/dadyarri/jacob/blob/d306c5542fd17773bb4916c78fac74090126f6d2/utils/rules.py#L11

payload можно отправлять со стороны пользователя, в таком случае будет вызвано исключение при десериализации

**Comment by dadyarri** [comment]
Спасибо за замечание, исправлено в da01801404473ab38b304ed546ae87fe7f3c56c3.
